sudo: required

language: minimal

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
  matrix:
    - PYTHON_VERSION=3.6 TEST_SUITE=python-tests

services:
  - docker

install :
  - docker build -t local-test --build-arg PYTHON_VERSION=$PYTHON_VERSION .

script:
  - docker run --rm local-test:latest bash -i -c "pytest"